/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrsrIndexRouteImport } from './routes/brsr.index'
import { Route as BrsrAssuranceRouteImport } from './routes/brsr.assurance'
import { Route as BrsrGeneralDisclosuresRouteImport } from './routes/brsr.general-disclosures'
import { Route as BrsrManagementProcessRouteImport } from './routes/brsr.management-process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrsrIndexRoute = BrsrIndexRouteImport.update({
  id: '/brsr/',
  path: '/brsr/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrsrAssuranceRoute = BrsrAssuranceRouteImport.update({
  id: '/brsr/assurance',
  path: '/brsr/assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const BrsrGeneralDisclosuresRoute = BrsrGeneralDisclosuresRouteImport.update({
  id: '/brsr/general-disclosures',
  path: '/brsr/general-disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const BrsrManagementProcessRoute = BrsrManagementProcessRouteImport.update({
  id: '/brsr/management-process',
  path: '/brsr/management-process',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brsr/assurance': typeof BrsrAssuranceRoute
  '/brsr/general-disclosures': typeof BrsrGeneralDisclosuresRoute
  '/brsr/management-process': typeof BrsrManagementProcessRoute
  '/brsr/': typeof BrsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brsr/assurance': typeof BrsrAssuranceRoute
  '/brsr/general-disclosures': typeof BrsrGeneralDisclosuresRoute
  '/brsr/management-process': typeof BrsrManagementProcessRoute
  '/brsr': typeof BrsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brsr/assurance': typeof BrsrAssuranceRoute
  '/brsr/general-disclosures': typeof BrsrGeneralDisclosuresRoute
  '/brsr/management-process': typeof BrsrManagementProcessRoute
  '/brsr/': typeof BrsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brsr/assurance'
    | '/brsr/general-disclosures'
    | '/brsr/management-process'
    | '/brsr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brsr/assurance'
    | '/brsr/general-disclosures'
    | '/brsr/management-process'
    | '/brsr'
  id:
    | '__root__'
    | '/'
    | '/brsr/assurance'
    | '/brsr/general-disclosures'
    | '/brsr/management-process'
    | '/brsr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrsrAssuranceRoute: typeof BrsrAssuranceRoute
  BrsrGeneralDisclosuresRoute: typeof BrsrGeneralDisclosuresRoute
  BrsrManagementProcessRoute: typeof BrsrManagementProcessRoute
  BrsrIndexRoute: typeof BrsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brsr/': {
      id: '/brsr/'
      path: '/brsr'
      fullPath: '/brsr/'
      preLoaderRoute: typeof BrsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brsr/assurance': {
      id: '/brsr/assurance'
      path: '/brsr/assurance'
      fullPath: '/brsr/assurance'
      preLoaderRoute: typeof BrsrAssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brsr/general-disclosures': {
      id: '/brsr/general-disclosures'
      path: '/brsr/general-disclosures'
      fullPath: '/brsr/general-disclosures'
      preLoaderRoute: typeof BrsrGeneralDisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brsr/management-process': {
      id: '/brsr/management-process'
      path: '/brsr/management-process'
      fullPath: '/brsr/management-process'
      preLoaderRoute: typeof BrsrManagementProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrsrAssuranceRoute: BrsrAssuranceRoute,
  BrsrGeneralDisclosuresRoute: BrsrGeneralDisclosuresRoute,
  BrsrManagementProcessRoute: BrsrManagementProcessRoute,
  BrsrIndexRoute: BrsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
